import { Inter, Montserrat } from 'next/font/google';
import './globals.css';
import SessionProvider from './components/SessionProvider';
import NavMenu from './components/NavMenu';
import { getServerSession } from 'next-auth';

const monte = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={monte.className}>
        {/* <NavMenu /> */}
        <div classname="h-full relative ">
          <SessionProvider session={session}>
            <main className="bg-[#F8FAFF]">{children}</main>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
